version: "3.9"

services:
  nhstt-door-system-web:
    build: ./web
    ports:
      - "3004:80"
    restart: unless-stopped
    networks:
      - nhstt-door-system
    environment:
      DB_HOST: 192.168.1.21
      DB_NAME: door_dev
      DB_USER: root
      DB_PASS: Superce11ular!
      LDAP_HOST: "ldaps://192.168.1.251"
      LDAP_DN: "DC=techteam,DC=local"
      MQTT_URL: "mqtt://192.168.1.21:9001/mqtt"
      MQTT_USERNAME: "admin"
      MQTT_PASSWORD: "superce11"
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/New_York
    ports:
      - "1880:1880"
    networks:
      - nhstt-door-system
    volumes:
      - ./nodered/data:/data

networks:
  - nhstt-door-system