services:
  nhstt-door-system-web:
    build: ./web
    ports:
      - "3004:80"
    restart: unless-stopped
    networks:
      - nhstt-door-system
    environment:
      DB_HOST: 192.168.1.21
      DB_NAME: door_dev
      DB_USER: root
      DB_PASS: Superce11ular!
      LDAP_HOST: "ldaps://192.168.1.251"
      LDAP_DN: "DC=techteam,DC=local"
      MQTT_URL: "mqtt://192.168.1.21:9001/mqtt"
      MQTT_USERNAME: "admin"
      MQTT_PASSWORD: "superce11"
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/New_York
    ports:
      - "1880:1880"
    networks:
      - nhstt-door-system
    volumes:
      - ./nodered/data:/data
    #This allows the container to talk to the Arduino for RFID and the USB relay
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/hidraw0:/dev/hidraw0"

    #permission stuff b/c its locked down by default
    group_add:
      - "20"   # replace with your dialout GID
    privileged: true
  mqtt:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    expose:
      - "1883"
    networks:
      - nhstt-door-system
    #volumes:
    #  - ./mqtt/config:/mosquitto/config
  gui:

    image: ubuntu:24.04

    environment:

      DISPLAY: ${DISPLAY}

    volumes:

      - /tmp/.X11-unix:/tmp/.X11-unix

    stdin_open: true

    tty: true

networks:
  nhstt-door-system: